#!/bin/bash
RULE_ID=$1
grep -F '"'$RULE_ID'"' /var/ossec/logs/archives/archives.json | jq -c 'select ( .rule.id == "'$RULE_ID'" )' | head -n1 > /tmp/sample.json
jq .full_log /tmp/sample.json | sed 's/\\"/"/g;s/\\\\/\\/g;s/^"//;s/"$//'
