#!/bin/bash

DBG=1;

function tprobe() {
        if [ "$DBG" == "1" ]; then echo "Preparing to probe $1 on port $2..."; fi
        if [[ `echo $1 | grep -P "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$"` ]]; then
                if [ "$DBG" == "1" ]; then echo "$1 appears to be an IP number."; fi
                tpr_ip=$1
        else
                if [ "$DBG" == "1" ]; then echo "Looking up IP for host $1..."; fi
                tpr_ip=`getent hosts $1 | awk '{ print $1 }' | head -n1`
        fi
        if [ "$tpr_ip" == "" ]; then
                if [ "$DBG" == "1" ]; then echo "*** Failed to find IP for $1."; fi
                exit 0
        fi
        if [ "$DBG" == "1" ]; then echo "Probing $tpr_ip:$2..."; fi
        echo > /dev/tcp/$tpr_ip/$2 &
        sleep 2
        if [[ `ps auxw | awk '{print $2}' | egrep "^$!"` ]]; then
                if [ "$DBG" == "1" ]; then echo "*** Failed to get response from $1 on tcp/$2."; fi
                kill $!
                exit 0
        fi
        if [ "$DBG" == "1" ]; then echo "Success!"; fi
}

# example call
tprobe www.google.com 443
# if the above fails

# another example call
tprobe 8.8.4.4 443
